import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  bookSidebar: [
    {
      type: 'category',
      label: 'Part I: Foundations of Physical AI',
      items: [
        'part-i/chapter-1-introduction-to-physical-ai',
        'part-i/chapter-2-humanoid-robotics-landscape',
      ],
    },
    {
      type: 'category',
      label: 'Part II: The Robotic Nervous System (ROS 2)',
      items: [
        'part-ii/chapter-3-ros-2-architecture',
        'part-ii/chapter-4-building-ros-2-packages',
        'part-ii/chapter-5-urdf-and-humanoid-robot-description',
      ],
    },
    {
      type: 'category',
      label: 'Part III: The Digital Twin (Gazebo & Unity)',
      items: [
        'part-iii/chapter-6-gazebo-simulation-fundamentals',
        'part-iii/chapter-7-unity-robotics-integration',
        'part-iii/chapter-8-building-the-digital-twin',
      ],
    },
    {
      type: 'category',
      label: 'Part IV: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'part-iv/chapter-9-nvidia-isaac-sim',
        'part-iv/chapter-10-isaac-ros-and-perception',
        'part-iv/chapter-11-navigation-and-bipedal-planning',
      ],
    },
    {
      type: 'category',
      label: 'Part V: Vision-Language-Action (VLA)',
      items: [
        'part-v/chapter-12-voice-to-action-systems',
        'part-v/chapter-13-cognitive-planning-with-llms',
        'part-v/chapter-14-embodied-vla-models',
      ],
    },
    {
      type: 'category',
      label: 'Part VI: RAG-Powered Book Chatbot',
      items: [
        'part-vi/chapter-15-building-the-rag-chatbot-backend',
        'part-vi/chapter-16-docusaurus-chatbot-integration',
      ],
    },
    {
      type: 'category',
      label: 'Part VII: Humanoid Robot Engineering',
      items: [
        'part-vii/chapter-17-humanoid-kinematics-and-dynamics',
        'part-vii/chapter-18-manipulation-and-dexterous-hands',
        'part-vii/chapter-19-natural-human-robot-interaction',
      ],
    },
    {
      type: 'category',
      label: 'Part VIII: Capstone Project',
      items: [
        'part-viii/chapter-20-the-final-system',
        'part-viii/chapter-21-sim-to-real-deployment',
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [
        'appendices/a-hardware-requirements',
        'appendices/b-cloud-vs-on-premise',
        'appendices/c-jetson-edge-kit-setup',
        'appendices/d-docusaurus-github-pages-deployment',
        'appendices/e-ros-2-cheat-sheets',
        'appendices/f-safety-protocols-for-humanoids',
      ],
    },
  ],
};

export default sidebars;
